---
timezone: Asia/Ho_Chi_Minh
ansible_port: 22
ansible_user: soulevil

#apt_packages:
#  - net-tools
disable_apt_update: true
swapoff: false

ulimit:
  nofile: 655350
  core: unlimited
  noproc: unlimited

sysctl_file: /etc/sysctl.d/60-custom-tunning.conf

sysctl_config:
  fs.file-max: 655350
  fs.inotify.max_queued_events: 16384
  fs.inotify.max_user_instances: 8192
  fs.inotify.max_user_watches: 12288
  kernel.core_pattern: "/var/coredump/core.%e.%p.%t"
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.arp_filter: 0
  net.ipv4.conf.default.arp_filter: 0
  net.ipv4.ip_forward: 1
  net.ipv4.ip_local_port_range: 1024 65535
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv6.conf.all.forwarding: 1

node_exporter_version: '1.3.1'
redis_exporter_version: '1.43.0'
memcached_exporter_version: '0.10.0'
mongodb_exporter_version: '0.32.0'
mongodb_exporter_options: '--mongodb.uri=mongodb://mongodb_exporter:s3cr3tpassw0rd@127.0.0.1:27017 --collect-all'

redis_version: 7.0.2
redis_install_dir: /opt/redis

postgresql_exporter_version: '0.10.1'