- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone XCrawler
  become_user: "{{ansible_user}}"
  git:
    repo: "{{ github_url}}"
    dest: /home/{{ansible_user}}/XCrawler

- name: Checkout master
  become_user: "{{ansible_user}}"
  shell:
    chdir: ~/XCrawler
    cmd: git checkout -f {{default_branch}}

- name: Pull
  become_user: "{{ansible_user}}"
  shell:
    chdir: ~/XCrawler
    cmd: git pull

- name: Copy .env
  become_user: "{{ansible_user}}"
  template:
    src: .env
    dest: ~/XCrawler
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    force: true
    mode: 0644

- name: Composer install
  become_user: "{{ansible_user}}"
  shell:
    chdir: ~/XCrawler
    cmd: composer install
