---
physical:
  hosts:
    gatekeeper:
      ansible_host: gatekeeper
      ansible_user: soulevil

x300:
  hosts:
    barista:
      ansible_host: barista
      ansible_user: barista
    coffeeschool:
      ansible_host: coffeeschool
      ansible_user: coffeeschool
    redis_develop:
      ansible_host: redis_develop
      ansible_user: soulevil
    hosting:
      ansible_host: hosting
      ansible_user: soulevil

workstation:
  hosts:
    smb:
      ansible_host: smb
      ansible_user: soulevil
    mysql:
      ansible_host: mysql
      ansible_user: soulevil
    mongodb:
      ansible_host: mongodb
      ansible_user: soulevil
    redis:
      ansible_host: redis
      ansible_user: soulevil
    testing:
      ansible_host: testing
      ansible_user: soulevil
    runners:
      ansible_host: runners
      ansible_user: soulevil