---
- name: Setup basic configurations
  import_tasks: base.yml
  tags: base

- name: Tunning modules values
  import_tasks: modules.yml
  tags: modules

- name: Config limit.conf
  import_tasks: limit.yml
  tags: limit

- name: tunning sysctl values
  import_tasks: sysctl.yml
  tags: sysctl

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot reminder
  debug:
    msg: ">> NOTICE: reboot is required for some settings to be effected (selinux, update 1st..)"
  when: reboot_required_file.stat.exists

- name: Reboot a Linux machine
  reboot:
    reboot_timeout: 1800
  when: reboot_required_file.stat.exists