## APT
#- name: Installs the ppa:ondrej/php repo on Ubuntu systems
#  apt_repository:
#    repo: ppa:ondrej/php
#    update_cache: true

#- name: Install PHP
#  apt:
#    pkg:
#      - php{{ php_version }}
#      - php{{ php_version }}-dev
#      - php{{ php_version }}-cli
#      - php{{ php_version }}-mbstring
#      - php{{ php_version }}-curl
#      - php{{ php_version }}-intl
#      - php{{ php_version }}-xml
#      - php{{ php_version }}-xmlrpc
#      - php{{ php_version }}-xsl
#      - php{{ php_version }}-yaml
#      - php{{ php_version }}-zip
#      - php{{ php_version }}-imagick
#      - php{{ php_version }}-gd
#      - php{{ php_version }}-opcache
#      - php{{ php_version }}-memcached
#      - php{{ php_version }}-memcache
#      - php{{ php_version }}-mysql
#      - php{{ php_version }}-sqlite3
#      - php{{ php_version }}-bcmath
#      - php{{ php_version }}-fpm
#    state: latest
#    update_cache: true

#- name: Install PHP Composer
#  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#  args:
#    creates: /usr/local/bin/composer

#- name: Install Pecl Extensions
#  shell: pecl -d php_suffix="{{ php_version }}" install {{ item }}
#  with_items:
#    - apcu
#    - redis
#    - pcov
#    - mongodb

- name: Setup extensions
  lineinfile:
    path: /etc/php/{{ php_version }}/cli/php.ini
    search_string: "{{ item }}"
    line: "{{ item }}"
  with_items:
    - "extension=apcu.so"
    - "extension=redis.so"
    - "extension=pcov.so"
    - "extension=mongodb.so"