---
- name: Check current memcached_exporter version.
  command: "{{ memcached_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: memcached_exporter_version_check

- name: Download and unarchive memcached_exporter into temporary location.
  unarchive:
    src: "{{ memcached_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >
    memcached_exporter_version_check.stdout is not defined
    or memcached_exporter_version not in memcached_exporter_version_check.stdout
  register: memcached_exporter_download_check

- name: Move memcached_exporter binary into place.
  copy:
    src: "/tmp/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ memcached_exporter_arch }}/memcached_exporter"
    dest: "{{ memcached_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart memcached_exporter
  when: memcached_exporter_download_check is changed

- name: Create memcached_exporter user.
  user:
    name: memcached_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the memcached_exporter systemd unit file.
  template:
    src: memcached_exporter.service.j2
    dest: /etc/systemd/system/memcached_exporter.service
    mode: 0644
  register: memcached_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart memcached_exporter
  when: memcached_exporter_service is changed

- name: Ensure memcached_exporter is running and enabled at boot.
  service:
    name: memcached_exporter
    state: "{{ memcached_exporter_state }}"
    enabled: "{{ memcached_exporter_enabled }}"

- name: Verify memcached_exporter is responding to requests.
  uri:
    url: http://localhost:9150/
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
